/**
 * CINEVERSE Movie Database
 * Rich movie catalog with metadata, trailers, cast, and categorization.
 */

export const MOVIES = [
  {
    id: 'dark-knight',
    title: 'The Dark Knight',
    tagline: 'Why so serious?',
    year: 2008,
    rating: 9.0,
    duration: '2h 32m',
    maturity: 'PG-13',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Action', 'Crime', 'Drama'],
    featured: true,
    trending: true,
    popular: true,
    topRated: true,
    category: 'action',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'EXeTwQWrcwY', // Official Trailer
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Gary Oldman', 'Morgan Freeman'],
    tags: ['Superhero', 'Vigilante', 'Masterpiece', 'Oscar Winner']
  },
  {
    id: 'dune-2',
    title: 'Dune: Part Two',
    tagline: 'Long live the fighters.',
    year: 2024,
    rating: 8.6,
    duration: '2h 46m',
    maturity: 'PG-13',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    featured: true,
    trending: true,
    popular: true,
    topRated: true,
    category: 'scifi',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'Way9Dexny3w',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family, facing a choice between love and the fate of the known universe.',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Austin Butler', 'Florence Pugh'],
    tags: ['Epic Sci-Fi', 'Space Saga', 'Visual Splendor', 'Blockbuster']
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    year: 2023,
    rating: 8.9,
    duration: '3h 00m',
    maturity: 'R',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Biography', 'Drama', 'History'],
    featured: true,
    trending: true,
    popular: true,
    topRated: true,
    category: 'drama',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'uYPbbksJxIg',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project, exploring the moral complexity of scientific breakthrough.',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'],
    tags: ['Academy Award Winner', 'Historical Drama', 'Intense', 'Nolan Masterpiece']
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    year: 2014,
    rating: 8.7,
    duration: '2h 49m',
    maturity: 'PG-13',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    featured: true,
    trending: false,
    popular: true,
    topRated: true,
    category: 'scifi',
    poster: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'zSWdZVtXT7E',
    description: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    tags: ['Black Hole', 'Deep Space', 'Emotional', 'Mind-Bending']
  },
  {
    id: 'inception',
    title: 'Inception',
    tagline: 'Your mind is the scene of the crime.',
    year: 2010,
    rating: 8.8,
    duration: '2h 28m',
    maturity: 'PG-13',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    featured: false,
    trending: true,
    popular: true,
    topRated: true,
    category: 'action',
    poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'YoHD9XEInc0',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy', 'Ken Watanabe'],
    tags: ['Heist', 'Dream Logic', 'Thriller', 'Cult Classic']
  },
  {
    id: 'cyberpunk-edgerunners',
    title: 'Cyberpunk: Edgerunners',
    tagline: 'Go out with a bang.',
    year: 2022,
    rating: 8.3,
    duration: '10 Episodes',
    maturity: 'TV-MA',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Animation', 'Action', 'Sci-Fi'],
    featured: true,
    trending: true,
    popular: true,
    topRated: false,
    category: 'animation',
    poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'JtqIas3bYhg',
    description: 'A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner: a mercenary outlaw.',
    director: 'Hiroyuki Imaishi',
    cast: ['KENN', 'Aoi Yuuki', 'Hiroki Touchi', 'Michiko Kaiden'],
    tags: ['Anime', 'Neon', 'Cyberpunk', 'High Octane']
  },
  {
    id: 'spider-verse',
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'It is how you wear the mask that matters.',
    year: 2023,
    rating: 8.7,
    duration: '2h 20m',
    maturity: 'PG',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Animation', 'Action', 'Adventure'],
    featured: false,
    trending: true,
    popular: true,
    topRated: true,
    category: 'animation',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'cqGjhVJWtEg',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
    director: 'Joaquim Dos Santos, Kemp Powers',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Daniel Kaluuya'],
    tags: ['Multiverse', 'Innovative Animation', 'Visual Tour de Force']
  },
  {
    id: 'stranger-things',
    title: 'Stranger Things',
    tagline: 'Every ending has a beginning.',
    year: 2022,
    rating: 8.7,
    duration: '4 Seasons',
    maturity: 'TV-14',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Drama', 'Fantasy', 'Horror'],
    featured: false,
    trending: true,
    popular: true,
    topRated: true,
    category: 'drama',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'b9EkMc79ZSU',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    director: 'The Duffer Brothers',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder', 'David Harbour'],
    tags: ['80s Nostalgia', 'Supernatural', 'Binge-Worthy', 'Mystery']
  },
  {
    id: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    tagline: 'The key to the future is finally unearthed.',
    year: 2017,
    rating: 8.0,
    duration: '2h 44m',
    maturity: 'R',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Sci-Fi', 'Action', 'Mystery'],
    featured: false,
    trending: false,
    popular: true,
    topRated: false,
    category: 'scifi',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'gCcx85zbxz4',
    description: 'Young Blade Runner K unearths a long-buried secret that has the potential to plunge what is left of society into chaos. K track down former Blade Runner Rick Deckard, missing for thirty years.',
    director: 'Denis Villeneuve',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks'],
    tags: ['Neo-Noir', 'Atmospheric', 'Stunning Cinematography']
  },
  {
    id: 'gladiator-2',
    title: 'Gladiator II',
    tagline: 'What we do in life echoes in eternity.',
    year: 2024,
    rating: 8.1,
    duration: '2h 28m',
    maturity: 'R',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Action', 'Adventure', 'Drama'],
    featured: false,
    trending: true,
    popular: true,
    topRated: false,
    category: 'action',
    poster: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?auto=format&fit=crop&w=1920&q=80',
    trailerId: '4rgYUipGJNo',
    description: 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.',
    director: 'Ridley Scott',
    cast: ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'],
    tags: ['Colosseum', 'Roman Empire', 'Sword & Sandal', 'Epic']
  },
  {
    id: 'john-wick-4',
    title: 'John Wick: Chapter 4',
    tagline: 'No way back. One way out.',
    year: 2023,
    rating: 8.2,
    duration: '2h 49m',
    maturity: 'R',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Action', 'Crime', 'Thriller'],
    featured: false,
    trending: true,
    popular: true,
    topRated: false,
    category: 'action',
    poster: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'qEVUtrk8_B4',
    description: 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Laurence Fishburne'],
    tags: ['Martial Arts', 'Gun-Fu', 'Stylish', 'Adrenaline']
  },
  {
    id: 'arcane',
    title: 'Arcane: League of Legends',
    tagline: 'Blood runs thicker than hextech.',
    year: 2021,
    rating: 9.0,
    duration: '2 Seasons',
    maturity: 'TV-14',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Animation', 'Action', 'Sci-Fi'],
    featured: false,
    trending: true,
    popular: true,
    topRated: true,
    category: 'animation',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'fXmAurh012s',
    description: 'Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.',
    director: 'Pascal Charrue, Arnaud Delord',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro', 'Katie Leung'],
    tags: ['Steampunk', 'Masterpiece', 'Sisters', 'Emmy Winner']
  },
  {
    id: 'godfather',
    title: 'The Godfather',
    tagline: 'An offer you cannot refuse.',
    year: 1972,
    rating: 9.2,
    duration: '2h 55m',
    maturity: 'R',
    quality: '4K REMASTERED',
    audio: '5.1 SURROUND',
    genres: ['Crime', 'Drama'],
    featured: false,
    trending: false,
    popular: true,
    topRated: true,
    category: 'drama',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'sY1S34973zA',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Robert Duvall'],
    tags: ['Mafia', 'Classic', 'All-Time Great', 'Family']
  },
  {
    id: 'the-batman',
    title: 'The Batman',
    tagline: 'Unmask the truth.',
    year: 2022,
    rating: 7.9,
    duration: '2h 56m',
    maturity: 'PG-13',
    quality: '4K ULTRA HD',
    audio: 'DOLBY ATMOS',
    genres: ['Action', 'Crime', 'Drama'],
    featured: false,
    trending: false,
    popular: true,
    topRated: false,
    category: 'action',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'mqqft2x_Aa4',
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city hidden corruption and question his family involvement.',
    director: 'Matt Reeves',
    cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Colin Farrell'],
    tags: ['Detective', 'Dark Noir', 'Gotham', 'Riddler']
  },
  {
    id: 'pulp-fiction',
    title: 'Pulp Fiction',
    tagline: 'Just because you are a character does not mean that you have character.',
    year: 1994,
    rating: 8.9,
    duration: '2h 34m',
    maturity: 'R',
    quality: '4K ULTRA HD',
    audio: '5.1 SURROUND',
    genres: ['Crime', 'Drama'],
    featured: false,
    trending: false,
    popular: true,
    topRated: true,
    category: 'drama',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1920&q=80',
    trailerId: 's7EdQ4FqbhY',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    tags: ['Cult Classic', 'Non-linear', 'Dialogue', 'Tarantino']
  },
  {
    id: 'avatar-water',
    title: 'Avatar: The Way of Water',
    tagline: 'Return to Pandora.',
    year: 2022,
    rating: 7.8,
    duration: '3h 12m',
    maturity: 'PG-13',
    quality: '4K 3D HFR',
    audio: 'DOLBY ATMOS',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    featured: false,
    trending: false,
    popular: true,
    topRated: false,
    category: 'scifi',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80',
    trailerId: 'd9MyW72ELq0',
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang'],
    tags: ['Pandora', 'Ocean Visuals', 'James Cameron', 'Spectacle']
  }
];

export const CATEGORIES = [
  { id: 'trending', title: '🔥 Trending Now', filter: m => m.trending },
  { id: 'popular', title: '⭐ Popular on CineVerse', filter: m => m.popular },
  { id: 'action', title: '💥 Action & Adrenaline', filter: m => m.genres.includes('Action') },
  { id: 'scifi', title: '🚀 Sci-Fi & Speculative', filter: m => m.genres.includes('Sci-Fi') },
  { id: 'animation', title: '🎨 Animation & Anime', filter: m => m.genres.includes('Animation') },
  { id: 'topRated', title: '🏆 Top Rated Masterpieces', filter: m => m.topRated || m.rating >= 8.8 }
];

export const GENRE_FILTERS = [
  { id: 'all', label: 'All Titles' },
  { id: 'trending', label: '🔥 Trending' },
  { id: 'action', label: '💥 Action' },
  { id: 'scifi', label: '🚀 Sci-Fi' },
  { id: 'drama', label: '🎭 Drama' },
  { id: 'crime', label: '🕵️ Crime' },
  { id: 'animation', label: '🎨 Animation' }
];
